# Change baseurl before deploy
baseurl = "https://blog.rei.ac"
languageCode = "zh-hans"
theme = "hugo-theme-stack"
paginate = 8
title = "Rei's Blog"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "zh-hans"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

googleAnalytics = "UA-97060993-1"