# Configure main menu and social menu
[[main]]
identifier = "oldblog"
name = "旧站"
url = "https://rei.meta.io"
weight = 10000
    [main.params]
    icon = "home"
    newtab = true

[[social]]
identifier = "github"
name = "GitHub"
weight = 1
url = "https://github.com/ACRei"
    [social.params]
    icon = "brand-github"
    newtab = true

[[social]]
identifier = "twitter"
name = "Twitter"
weight = 2
url = "https://twitter.com/ReiAccept"
    [social.params]
    icon = "brand-twitter"
    newtab = true

[[social]]
identifier = "telegram"
name = "Telegram"
weight = 3
url = "https://t.me/ReiOnTheLoaf"
    [social.params]
    icon = "telegram"
    newtab = true

[[social]]
identifier = "Email"
name = "Email"
weight = 4
url = "mailto:lhh@live.com"
  [social.params]
  icon = "email"
  newTab = true

[[social]]
identifier = "RSS"
name = "RSS"
weight = 5
url = "/index.xml"
  [social.params]
  icon = "rss"
  newTab = true