# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

favicon = "https://avatars.githubusercontent.com/u/17238215"

[footer]
since = 2015
customText = ""

[dateFormat]
published = "2006 å¹´ 1 æœˆ 2 æ—¥"
lastUpdated = "2006 å¹´ 1 æœˆ 2 æ—¥ 15:04 CST"

[sidebar]
emoji = "ğŸ¤”"
subtitle = "ä¸€ä¸ªå°æœ‹å‹çš„äº’è”ç½‘è‡ªç•™åœ°"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = "ReiAccept"
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "ACRei/blog"
repoID = "R_kgDOGu8RsA"
category = "Announcements"
categoryID = "DIC_kwDOGu8RsM4COrU-"
mapping = "pathname"
lightTheme = "light"
darkTheme = "dark"
lang = "zh-CN"
reactionsEnabled = 1
emitMetadata = 0